baseURL: https://khanna-mehak.netlify.app/
languageCode: en-us
title: Mehak
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get To Know Me!
    subtitle: |-
      Currently playing with data, statistics and R programming while reading for Masters in Analytics & Management (MAM) at London Business School.
      
      THIS IS MY PORTFOLIO WEBSITE for AM01 Applied Statistics. 
    title: Hi, I am  Mehak Khanna
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Burton Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mkhanna.mam2023@london.edu
    enable: yes
    phone:
      - phone: +44-7767945085
        title: Phone
  custom_css: []
  custom_js: []
  description: Description 101
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Mehak
    enable: yes
    quicklinks:
      # - alt: HTML5 UP
      #   text: 'Design: '
      #   url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/khannamehak18
        
      # - icon: fa-facebook
      #  label: Facebook
      #  url: https://www.facebook.com/mehak.khanna.106
      
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/mehak___khanna
        
      - icon: fa-github
        label: GitHub
        url: https://github.com/khanna-mehak
        
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/khanna-mehak
  image: ''
  name: Mehak Khanna
  navigation:
    button1:
      - name: Get Started
        url: blogs
        
    # button2:
    #   - name: Log In
    #     url: '#'
        
    links:
      - name: Home
        url: '#'
      
      - name: Resume
        url: docs/CV.pdf 
        
      - name: Projects
        url: blogs/projects
        
      - name: Experiences
        url: blogs/experiences
         
      # - name: Elements
      #   url: elements.html
    menu: Menu
    subtitle: 
    title: Mehak's portfolio website
  tiles:
    enable: yes
    showcase:
      - image: abt_me.jpeg
        subtitle: Learn more about me!
        title: About me
        url: blogs/experiences/About_me
        
      - image: cv.png
        subtitle: My academic and professional journey         
        title: My CV
        url: docs/CV.pdf  
        
      - image: stock_analysis.jpeg
        subtitle: Stock Analsis project 
        title: Stock Analysis
        url: blogs/projects/stocks
        
      - image: san_fransisco.jpeg
        subtitle: In-depth analysis of rents across Bay area 
        title: San Fransisco Rent Analysis
        url: blogs/projects/sf_rent
        
      - image: brexit.jpeg
        subtitle: A vote analysis study for Brexit
        title: Brexit Poll Analysis
        url: blogs/projects/brexit
        
      - image: youth.png
        subtitle: Study of health pattern among high school students
        title: Health pattern analysis 
        url: blogs/projects/youth
        
      - image: gender.jpeg
        subtitle: Analysis of gender discrimination prevalent in salary
        title: Pay Discrimination
        url: blogs/projects/pay_disc  
        
      - image: travel_1.JPG
        subtitle: A collection of my favourite Travel memories
        title: My Travel Stories
        url: blogs/experiences/travel
        
     
  two:
    buttonText: Navigate to projects
    enable: yes
    subtitle: "I have always had a penchant for problem solving. 
              My academic and professional experiences have equipped me with skills in communication research such as content analysis and technical analysis and fostered a passion for data analytics. 
              Click below to navigate through some of my recent prejects."
    title: More about me!
    url: blogs/projects
  
  